### PR TITLE
Fix nginx fpm session file

### PR DESCRIPTION
**Pull request by FHenry**
- With nginx and php fpm if session_cache_limiter is after include main.inc.php the mime type "css"  is not send correctly to web browser
- Also use top_httphead dolibarr method is best practice like un eldy/style.css.php
I also recommand to review your PR #18977 witth this change

PS : Sorry for cleaning end space line

### CODE REVIEW

**Comment by FHenry** [comment]
@bb2a Hello, could you please take a look at this PR ?

**Comment by BB2A-Anthony** [comment]
@FHenry Sorry for your PR ok for you?
I change in my PR in [NEW - Module DropDownMenu #18977](https://github.com/Dolibarr/dolibarr/pull/18977)

**Comment by BB2A-Anthony** [comment]
@FHenry Tu peux parler en français.

**Comment by FHenry** [comment]
Super, merci pour le merge 😀

**Comment by BB2A-Anthony** [comment]
@FHenry J'ai changer dans mon PR vous pouvez commenter le PR?

**Pull request merged**
